# Site settings
title: "Simon Worthington - Personal Website"
description: >
  Simon Worthington, publishing nut

author: Simon Worthington
email: simon@metamute.org
twitter_username: _mrchristian99
github_username: mrchristian

baseurl: "/paper-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://deadbeef.me" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
